apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-appsets
  namespace: argocd
spec:
  project: default
  source:
    # TODO: Update this to your Git repository URL once committed
    repoURL: https://github.com/Reed-Schimmel/enterprise-ai-platform.git
    targetRevision: main
    path: charts/argocd-appsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
