{{- if .Values.crossplane.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crossplane
  namespace: argocd
  labels:
    app.kubernetes.io/name: crossplane-appset
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{ "{{" }}cluster{{ "}}" }}-crossplane'
      labels:
        app.kubernetes.io/name: crossplane
    spec:
      project: default
      source:
        repoURL: 'https://charts.crossplane.io/stable'
        targetRevision: {{ .Values.crossplane.targetRevision | quote }}
        chart: crossplane
        helm:
          releaseName: crossplane
      destination:
        server: '{{ "{{" }}url{{ "}}" }}'
        namespace: {{ .Values.crossplane.namespace | quote }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
{{- end }}
