apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: litellm-proxy
  namespace: argocd
  labels:
    app.kubernetes.io/name: litellm-proxy-appset
spec:
  generators:
    - git:
        repoURL: https://github.com/Reed-Schimmel/enterprise-ai-platform.git
        revision: litellm-proxy
        files:
          - path: configurations/**/litellm-proxy-config.yaml
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  template:
    metadata:
      name: {{`"{{ .path.basenameNormalized }}-litellm-proxy"`}}
      labels:
        cloud-provider: {{`"{{ index .path.segments 2 }}"`}}
        app.kubernetes.io/name: litellm-proxy
      annotations:
        argocd.argoproj.io/sync-wave: "5" # TODO: anything > -1
    spec:
      ignoreDifferences:
        - kind: Secret
          namespace: litellm-proxy
          name: litellm-proxy-dbcredentials
          jsonPointers:
          - /data
          - /metadata/annotations
        - kind: Secret
          namespace: litellm-proxy
          name: litellm-proxy-masterkey
          jsonPointers:
          - /data
      project: default
      source:
        repoURL: https://github.com/Reed-Schimmel/enterprise-ai-platform.git
        targetRevision: "litellm-proxy" # TODO: make dynamic from config values
        path: apps/litellm-proxy
        helm:
          releaseName: litellm-proxy
          valueFiles:
            - values.yaml
          values: |-
            {{`{{ .config }}`}}
      destination:
        server: https://kubernetes.default.svc
        namespace: litellm-proxy
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true # IMPORTANT
