apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/name: external-secrets-appset
spec:
  generators:
    - git:
        repoURL: https://github.com/Reed-Schimmel/enterprise-ai-platform.git
        revision: secret-manager
        files:
          - path: configurations/**/cluster-infra/external-secrets-config.yaml
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  template:
    metadata:
      name: '{{ index .path.segments 2 }}-external-secrets'
      labels:
        app.kubernetes.io/name: external-secrets
    spec:
      project: default
      source:
        repoURL: https://charts.external-secrets.io
        targetRevision: '{{ .targetRevision }}'
        chart: external-secrets
        helm:
          releaseName: external-secrets
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true