apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: reflector
  namespace: argocd
  labels:
    app.kubernetes.io/name: reflector-appset
spec:
  generators:
    - git:
        repoURL: https://github.com/Reed-Schimmel/enterprise-ai-platform.git
        revision: app-seps
        files:
          - path: configurations/**/cluster-infra/reflector-config.yaml
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  template:
    metadata:
      name: '{{ index .path.segments 2 }}-reflector'
      labels:
        app.kubernetes.io/name: reflector
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
    spec:
      project: default
      source:
        repoURL: https://emberstack.github.io/helm-charts
        targetRevision: '{{ .targetRevision }}'
        chart: reflector
        helm:
          releaseName: reflector
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true