apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-api-keys
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: litellm-proxy-api-keys
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: litellm/api-keys
